<?php
return array(
'WEBSITE'=>'http://www.puamap.com',
'WEBCDN'=>'http://www.puamap.com',
'WEBCOPY'=>'Copyright(c) 2016 浪迹教育    蜀ICP备13017604号-1',
'WEBTITLE'=>'浪迹PUA实战泡妞把妹社区 - 浪迹教育',
'WEBKWORDS'=>'pua,浪迹pua,把妹,浪迹,浪迹教育,浪迹团队',
'WEBDESC'=>'浪迹教育是中国最具影响力的实战PUA泡妞把妹教育机构,浪迹PUA教学涵盖把妹、搭讪、聊天、视频等。经过五年的发展,浪迹教育已成为中国规模最大的实战PUA泡妞把妹培训平台',
'ONOFF'=>'1',
'WEBNAME'=>'浪迹教育',
'WEBEMAIL'=>'380081006@qq.com',
'LINKMAN'=>'张倩',
'WEBTEL'=>'13408187117',
'ADDRESS'=>'',
'IMAGES_ALLOWEXT'=>'jpg|jpeg|gif|png',
'UPLOAD_DIR'=>'Public/uploads',
'THUMB_WIDTH'=>'300',
'THUMB_HEIGHT'=>'200',
'IMAGE_MINWIDTH'=>'100',
'IMAGE_MINHEIGHT'=>'100',
'WATER_TRANS'=>'50',
'WATER_PATH'=>'Public/watermark.png',
'UPLOAD_WATER_PLACE'=>'1',
'IS_CUT'=>'1',
'WATER_ISWATERMARK'=>'1',
);